name: GitHub Actions Demo
on: 
  push:
    branches:
    - feature/*
jobs:
  build_ios:
    name: build and deploy
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.1'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios --release --no-codesign
    - name: Upload iPA
      uses: actions/upload-artifact@master
      with:
        name: ios-build
        path: build/ios/iphoneos
  beta_ios:
    name: Upload iOS Beta to Firebase App Distribution
    needs: [build_ios]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: ios-build
        path: build/ios/iphoneos
    - name: print list
      run: ls
    - name: print current dir
      run: echo $PWD
    - name: check file exists
      run: |
        FILE=build/ios/iphoneos/Runner.ipa
        if [ -f "$FILE" ]; then
          echo "$FILE exists."
        else 
          echo "$FILE does not exist."
        fi
    - name: Upload IPA
      uses: wzieba/Firebase-Distribution-Github-Action@v1.0.0
      with:
        appId: ${{secrets.FIREBASE_IOS_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: build/ios/iphoneos/Runner.ipa
